name: SSH Remote Commands on Main Branch

on:
  push:
    branches:
      - fishyer

env:
  GIT_REMOTE: git@git.fishyer.com:fishyer/crm-pengqi.git
  GIT_BRANCH: fishyer
  PROJECT_PATH: /app/crm-pengqi

jobs:
  ssh-remote-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands using password on specific port
      uses: appleboy/ssh-action@master
      with:
        host: 104.168.59.18
        port: 22
        username: root
        password: E1amTBA8G2u4Oa8tu5
        script: |
          echo "Start Remote SSH commands"
          if [ -d ${{ env.PROJECT_PATH }} ]; then
            echo "${{ env.PROJECT_PATH }} 文件夹存在，进入文件夹并执行git pull"
            cd ${{ env.PROJECT_PATH }} || exit
            git pull -f origin ${{ env.GIT_BRANCH }}
            git fetch --tags
            cd ${{ env.PROJECT_PATH }} || exit
            sh ${{ env.PROJECT_PATH }}/.husky/shell/server-update.sh
          else
            echo "${{ env.PROJECT_PATH }} 文件夹不存在，执行git clone"
            git clone -b ${{ env.GIT_BRANCH }} ${{ env.GIT_REMOTE }} ${{ env.PROJECT_PATH }}
            git fetch --tags
            cd ${{ env.PROJECT_PATH }} || exit
            sh ${{ env.PROJECT_PATH }}/.husky/shell/server-init.sh
          fi
          sh ${{ env.PROJECT_PATH }}/.husky/post-push.sh
          echo "Stop Remote SSH commands"