#!/bin/bash
source ./.husky/template.sh

start_time=$(date +%s)
log "✅Running post-commit hook..."

source ./.husky/shell/config-read.sh
log "post-commit version: $build_type $build_version $build_time"

commit_hash=$(git rev-parse HEAD)  
log "Latest Commit hash: $commit_hash"
commit_message=$(git log -1 --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset')
log "Latest Commit message: $commit_message"

# 打版本tag
git tag -a "v$build_version" "$commit_hash" -m "v$build_version"

ent_time=$(date +%s)
log "🎉Success post-commit hook. Time elapsed: $((ent_time-start_time))s"

# post-commit: 打印提交信息，打版本tag