#!/bin/bash
source ./.husky/shell/config-read.sh

# shellcheck disable=SC2034
start_time=$(date +%s)
log "✅Running pre-push hook..."

source ./.husky/shell/config-read.sh
log "pre-push config: $build_type $build_version $build_time"

# 后续可以考虑在pre-push中,在本地生成docker镜像,并推送到远程仓库,以实现远程部署
# log "Build docker-compose.yaml"
# sh ./.husky/shell/compose-build.sh

# done
ent_time=$(date +%s)
log "🎉Success pre-push hook. Time elapsed: $((ent_time-start_time))s"

# git push -f origin fishyer --no-verify 
# pre-push: 执行build.sh,生成构建产物. 将第2段的MinorVersion+1,并归零第3段的PatchVersion 1 2 3
# ps aux | grep git | grep -v grep | awk '{print $2}' | xargs kill