#!/bin/bash
source ./.husky/template.sh

rm -rf .husky/log

start_time=$(date +%s)
log "✅Running pre-commit hook..."

source .husky/shell/config-update.sh
log "pre-commit config: $build_type $build_version $build_time"

log "Modify docker-compose.yml"
sh .husky/shell/compose-modify.sh

# sed -i '' -E "s/助贷系统v[0-9]+\.[0-9]+\.[0-9]+/助贷系统v$build_version/g" ./php/application/admin/view/auth.index.html
# git add "./php/application/admin/view/auth.index.html"

ent_time=$(date +%s)
log "🎉Success pre-commit hook. Time elapsed: $((ent_time-start_time))s"